---
# setup nginx

# Check whether the web configuration needs to be regenerated

# TODO: How do we know whether to regenerate the config when omero-web is
# upgraded using pip?
# This might be a good time to implement
# https://github.com/ome/openmicroscopy/pull/5994
# so that we always attempt to template the configuration and ansible takes care
# of figuring out whether it's chagned or not

- name: omero web | check web timestamp
  stat:
    follow: false
    path: "{{ omero_web_basedir }}/{{ omero_web_symlink }}"
  register: omero_web_st

- name: omero web | check nginx timestamp
  stat:
    path: /etc/nginx/conf.d/omero-web.conf
  register: omero_web_nginx_st

- name: omero web | check if nginx upgrade needed
  set_fact:
    omero_web_nginx_update_needed: >
      {{ (not omero_web_nginx_st.stat.exists) or
         (omero_web_nginx_st.stat.ctime < omero_web_st.stat.ctime)
      }}

- debug:
    msg: "Nginx configuration needed? {{ omero_web_nginx_update_needed }}"

# This will generate a warning about running su, ignore it since we need to run
# as root for the redirection
- name: omero web | generate nginx config
  become: true
  shell: >
    su {{ omero_web_system_user }} -lc
    "{{ omero_web_omero_command }} web config nginx"
    > /etc/nginx/conf.d/omero-web.conf
  when: omero_web_nginx_update_needed
  notify: restart nginx

- name: omero web | nginx remove system defaults
  become: true
  replace:
    backup: true
    dest: /etc/nginx/nginx.conf
    regexp: '80\s*default_server\s*;'
    replace: '80; # default_server;'
  notify: restart nginx

- name: omero web | enable nginx
  become: true
  service:
    enabled: true
    name: nginx
    state: started

# SELinux should be handled by openmicroscopy.omero-web-runtime
